### ISSUE TITLE
Set MaxKernel in README

### ISSUE THREAD

**Issue by averycblack** [AppleBluetooth/IntelBluetoothFamily#12]
It may be worth adding a note that you can set MaxKernel to 20.99.9 to allow this kext in Big Sur and older versions. Some people may dual boot Monterey and older versions, which could create issues if people copy and paste from the README. 20.99.9 should cover any updates in Big Sur, and it's the value I use for Itlwm on my config.

**Comment by 1demp0tence** [comment]
Good idea! I will make the change in the README. Thank you!
